import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  await prisma.product.createMany({
    data: [
      {
        name: 'Camiseta Algodón Orgánico',
        description: 'Camiseta básica de algodón orgánico, color blanco.',
        price: 12.99,
        sellerName: 'EcoModa',
        sellerId: '1',
        photo1Url: '/images/Item1.jpeg',
        photo2Url: '/images/Item2.jpeg',
        garmentType: 'Camiseta',
        color: 'Blanco',
        gender: 'Unisex',
        size: 'M',
        material: 'Algodón',
        country: 'Bangladesh',
        condition: 'Nuevo',
        brand: 'EcoModa',
        impactCo2: '2.7',
        impactWater: '480',
        impactEff: 'A',
      },
      {
        name: 'Pantalón Vaquero Reciclado',
        description: 'Jeans hechos con fibras recicladas, azul claro.',
        price: 29.99,
        sellerName: 'GreenDenim',
        sellerId: '2',
        photo1Url: '/images/Item3.jpeg',
        photo2Url: '/images/Item4.jpeg',
        garmentType: 'Pantalón',
        color: 'Azul',
        gender: 'Hombre',
        size: 'L',
        material: 'Mezcla (Algodón/Poliéster)',
        country: 'Turquía',
        condition: 'Usado',
        brand: 'GreenDenim',
        impactCo2: '4.2',
        impactWater: '900',
        impactEff: 'B',
      },
      {
        name: 'Vestido Lino',
        description: 'Vestido de lino natural, ideal para verano.',
        price: 39.99,
        sellerName: 'NaturalWear',
        sellerId: '3',
        photo1Url: '/images/Item5.jpeg',
        photo2Url: '/images/Item6.jpeg',
        garmentType: 'Vestido',
        color: 'Beige',
        gender: 'Mujer',
        size: 'S',
        material: 'Lino',
        country: 'Portugal',
        condition: 'Nuevo',
        brand: 'NaturalWear',
        impactCo2: '1.8',
        impactWater: '300',
        impactEff: 'A',
      },
      {
        name: 'Sudadera Poliéster Reciclado',
        description: 'Sudadera cómoda hecha de poliéster reciclado.',
        price: 24.99,
        sellerName: 'ReWear',
        sellerId: '4',
        photo1Url: '/images/Item2.jpeg',
        photo2Url: '/images/Item1.jpeg',
        garmentType: 'Sudadera',
        color: 'Gris',
        gender: 'Unisex',
        size: 'XL',
        material: 'Poliéster',
        country: 'China',
        condition: 'Nuevo',
        brand: 'ReWear',
        impactCo2: '3.1',
        impactWater: '600',
        impactEff: 'B',
      },
      {
        name: 'Falda Algodón',
        description: 'Falda ligera de algodón, color rosa pastel.',
        price: 19.99,
        sellerName: 'ModaCircular',
        sellerId: '5',
        photo1Url: '/images/Item4.jpeg',
        photo2Url: '/images/Item3.jpeg',
        garmentType: 'Falda',
        color: 'Rosa',
        gender: 'Mujer',
        size: 'M',
        material: 'Algodón',
        country: 'India',
        condition: 'Usado',
        brand: 'ModaCircular',
        impactCo2: '2.1',
        impactWater: '400',
        impactEff: 'A',
      },
    ]
  });
  console.log('Productos de ejemplo insertados.');
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect()); 